### ISSUE TITLE
Build Problems

### ISSUE THREAD

**Issue by linuzzx** [aria1th/PistonBoltPrinter#3]
* What went wrong:
Plugin [id: 'fabric-loom', version: '0.9-SNAPSHOT'] was not found in any of the following sources:

- Gradle Core Plugins (not a core plugin, please see https://docs.gradle.org/7.2/userguide/standard_plugins.html for available core plugins)
- Plugin Repositories (could not resolve plugin artifact 'fabric-loom:fabric-loom.gradle.plugin:0.9-SNAPSHOT')
  Searched in the following repositories:
    Gradle Central Plugin Repository

Any idea how to fix?

**Comment by aria1th** [comment]
solved at newer versions
